import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";
import pluginReact from "eslint-plugin-react";
import pluginReactHooks from "eslint-plugin-react-hooks";
import { defineConfig, globalIgnores } from "eslint/config";
import pluginRouter from "@tanstack/eslint-plugin-router";

export default defineConfig([
  globalIgnores([
    // Build output and tool caches
    "dist/",
    ".wrangler/",
    ".trigger/",
    ".tanstack/",
    ".pnpm-store/",
    // Generated — regenerated by `wrangler types` and the router plugin
    "worker-configuration.d.ts",
    "src/routeTree.gen.ts",
  ]),
  {
    files: ["**/*.{js,mjs,cjs,ts,mts,cts,jsx,tsx}"],
    plugins: { js },
    extends: ["js/recommended"],
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
    },
  },
  tseslint.configs.recommended,
  pluginReact.configs.flat.recommended,
  // React 19 uses the automatic JSX runtime, so `React` need not be in scope.
  pluginReact.configs.flat["jsx-runtime"],
  pluginReactHooks.configs.flat["recommended-latest"],
  ...pluginRouter.configs["flat/recommended"],
  {
    settings: { react: { version: "detect" } },
    rules: {
      // Types come from TypeScript, not runtime propTypes.
      "react/prop-types": "off",
      // Allow intentionally-ignored args and caught errors when prefixed with `_`.
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
          destructuredArrayIgnorePattern: "^_",
        },
      ],
    },
  },
]);
