id = 'audiobook-covers'
name = 'Audiobook Covers'
databaseType = 'postgresql'

[flyway]
locations = ["filesystem:migrations"]
validateMigrationNaming = true
environment = 'dev'

[environments.dev]
url = "jdbc:postgresql://db1.weldawadyathink.com:6432/audiobookcovers_dev?prepareThreshold=0"

[environments.prod]
url = "jdbc:postgresql://db1.weldawadyathink.com:6432/audiobookcovers?prepareThreshold=0"
