allowBuilds:
  "@depot/cli": true
  core-js: true
  esbuild: true
  protobufjs: true
  sharp: true
  workerd: true

nodeLinker: hoisted

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - "@duckdb/node-api"
  - core-js
  - esbuild
  - protobufjs
  - workerd

packageImportMethod: clone-or-copy
