nodeLinker: hoisted

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@playwright/browser-chromium'
  - '@tailwindcss/oxide'
  - argon2
  - aws-sdk
  - esbuild
  - protobufjs
  - sharp
  - unix-dgram
  - workerd

packageImportMethod: clone-or-copy

patchedDependencies:
  '@slonik/driver@48.10.0': patches/@slonik__driver@48.10.0.patch
