nodeLinker: hoisted

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@playwright/browser-chromium'
  - '@tailwindcss/oxide'
  - argon2
  - aws-sdk
  - esbuild
  - protobufjs
  - unix-dgram

packageImportMethod: clone-or-copy
