version: '3.7'

services:

  embedding-indexer:
    image: weldawadyathink/audiobookcovers-embedding-indexer:latest
    restart: unless-stopped
    networks:
      - apinet
    environment:
      DATABASE: ${DATABASE}
      CLIP_API_URL: http://clip:8080


  reddit-indexer:
    image: weldawadyathink/audiobookcovers-reddit-scraper:latest
    restart: unless-stopped
    networks:
      - supportnet
    environment:
      DATABASE: ${DATABASE}
      PRAW_CLIENT_ID: ${PRAW_CLIENT_ID}
      PRAW_CLIENT_SECRET: ${PRAW_CLIENT_SECRET}

  reddit-downloader:
    image: weldawadyathink/audiobookcovers-image-downloader:latest
    restart: unless-stopped
    networks:
      - supportnet
    environment:
      DATABASE: ${DATABASE}
      AWS_S3_REGION_NAME: auto
      AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      GOOGLE_APPLICATION_CREDENTIALS_JSON: ${GOOGLE_APPLICATION_CREDENTIALS_JSON}

networks:
  supportnet:
  apinet:
    external: true
