# fly.toml app configuration file generated for audiobookcovers-downloader on 2025-06-09T10:07:04+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'audiobookcovers-downloader'
primary_region = 'sjc'

[build]

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
