[project]
name = "audiobookcovers-downloader"
requires-python = ">=3.13,<4.0"
dependencies = [
    "bdfr (>=2.6.2,<3.0.0)",
    "praw (==7.7.0)"
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
