/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RandomRouteImport } from './routes/random'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContributeRouteImport } from './routes/contribute'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ImagesIdRouteImport } from './routes/images.$id'
import { Route as CoverBytextRouteImport } from './routes/cover.bytext'
import { Route as ApiLoginRouteImport } from './routes/api/login'
import { Route as ApiHeartbeatRouteImport } from './routes/api/heartbeat'
import { Route as AdminTestRouteImport } from './routes/admin/test'
import { Route as AdminSimilarRouteImport } from './routes/admin/similar'
import { Route as AdminLogoutRouteImport } from './routes/admin/logout'
import { Route as AdminDatabase_infoRouteImport } from './routes/admin/database_info'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RandomRoute = RandomRouteImport.update({
  id: '/random',
  path: '/random',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributeRoute = ContributeRouteImport.update({
  id: '/contribute',
  path: '/contribute',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ImagesIdRoute = ImagesIdRouteImport.update({
  id: '/images/$id',
  path: '/images/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverBytextRoute = CoverBytextRouteImport.update({
  id: '/cover/bytext',
  path: '/cover/bytext',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoginRoute = ApiLoginRouteImport.update({
  id: '/api/login',
  path: '/api/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHeartbeatRoute = ApiHeartbeatRouteImport.update({
  id: '/api/heartbeat',
  path: '/api/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestRoute = AdminTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSimilarRoute = AdminSimilarRouteImport.update({
  id: '/similar',
  path: '/similar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogoutRoute = AdminLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDatabase_infoRoute = AdminDatabase_infoRouteImport.update({
  id: '/database_info',
  path: '/database_info',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contribute': typeof ContributeRoute
  '/login': typeof LoginRoute
  '/random': typeof RandomRoute
  '/search': typeof SearchRoute
  '/admin/database_info': typeof AdminDatabase_infoRoute
  '/admin/logout': typeof AdminLogoutRoute
  '/admin/similar': typeof AdminSimilarRoute
  '/admin/test': typeof AdminTestRoute
  '/api/heartbeat': typeof ApiHeartbeatRoute
  '/api/login': typeof ApiLoginRoute
  '/cover/bytext': typeof CoverBytextRoute
  '/images/$id': typeof ImagesIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contribute': typeof ContributeRoute
  '/login': typeof LoginRoute
  '/random': typeof RandomRoute
  '/search': typeof SearchRoute
  '/admin/database_info': typeof AdminDatabase_infoRoute
  '/admin/logout': typeof AdminLogoutRoute
  '/admin/similar': typeof AdminSimilarRoute
  '/admin/test': typeof AdminTestRoute
  '/api/heartbeat': typeof ApiHeartbeatRoute
  '/api/login': typeof ApiLoginRoute
  '/cover/bytext': typeof CoverBytextRoute
  '/images/$id': typeof ImagesIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contribute': typeof ContributeRoute
  '/login': typeof LoginRoute
  '/random': typeof RandomRoute
  '/search': typeof SearchRoute
  '/admin/database_info': typeof AdminDatabase_infoRoute
  '/admin/logout': typeof AdminLogoutRoute
  '/admin/similar': typeof AdminSimilarRoute
  '/admin/test': typeof AdminTestRoute
  '/api/heartbeat': typeof ApiHeartbeatRoute
  '/api/login': typeof ApiLoginRoute
  '/cover/bytext': typeof CoverBytextRoute
  '/images/$id': typeof ImagesIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contribute'
    | '/login'
    | '/random'
    | '/search'
    | '/admin/database_info'
    | '/admin/logout'
    | '/admin/similar'
    | '/admin/test'
    | '/api/heartbeat'
    | '/api/login'
    | '/cover/bytext'
    | '/images/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contribute'
    | '/login'
    | '/random'
    | '/search'
    | '/admin/database_info'
    | '/admin/logout'
    | '/admin/similar'
    | '/admin/test'
    | '/api/heartbeat'
    | '/api/login'
    | '/cover/bytext'
    | '/images/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contribute'
    | '/login'
    | '/random'
    | '/search'
    | '/admin/database_info'
    | '/admin/logout'
    | '/admin/similar'
    | '/admin/test'
    | '/api/heartbeat'
    | '/api/login'
    | '/cover/bytext'
    | '/images/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContributeRoute: typeof ContributeRoute
  LoginRoute: typeof LoginRoute
  RandomRoute: typeof RandomRoute
  SearchRoute: typeof SearchRoute
  ApiHeartbeatRoute: typeof ApiHeartbeatRoute
  ApiLoginRoute: typeof ApiLoginRoute
  CoverBytextRoute: typeof CoverBytextRoute
  ImagesIdRoute: typeof ImagesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/random': {
      id: '/random'
      path: '/random'
      fullPath: '/random'
      preLoaderRoute: typeof RandomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribute': {
      id: '/contribute'
      path: '/contribute'
      fullPath: '/contribute'
      preLoaderRoute: typeof ContributeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/images/$id': {
      id: '/images/$id'
      path: '/images/$id'
      fullPath: '/images/$id'
      preLoaderRoute: typeof ImagesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cover/bytext': {
      id: '/cover/bytext'
      path: '/cover/bytext'
      fullPath: '/cover/bytext'
      preLoaderRoute: typeof CoverBytextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/login': {
      id: '/api/login'
      path: '/api/login'
      fullPath: '/api/login'
      preLoaderRoute: typeof ApiLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/heartbeat': {
      id: '/api/heartbeat'
      path: '/api/heartbeat'
      fullPath: '/api/heartbeat'
      preLoaderRoute: typeof ApiHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/test': {
      id: '/admin/test'
      path: '/test'
      fullPath: '/admin/test'
      preLoaderRoute: typeof AdminTestRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/similar': {
      id: '/admin/similar'
      path: '/similar'
      fullPath: '/admin/similar'
      preLoaderRoute: typeof AdminSimilarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logout': {
      id: '/admin/logout'
      path: '/logout'
      fullPath: '/admin/logout'
      preLoaderRoute: typeof AdminLogoutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/database_info': {
      id: '/admin/database_info'
      path: '/database_info'
      fullPath: '/admin/database_info'
      preLoaderRoute: typeof AdminDatabase_infoRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDatabase_infoRoute: typeof AdminDatabase_infoRoute
  AdminLogoutRoute: typeof AdminLogoutRoute
  AdminSimilarRoute: typeof AdminSimilarRoute
  AdminTestRoute: typeof AdminTestRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDatabase_infoRoute: AdminDatabase_infoRoute,
  AdminLogoutRoute: AdminLogoutRoute,
  AdminSimilarRoute: AdminSimilarRoute,
  AdminTestRoute: AdminTestRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContributeRoute: ContributeRoute,
  LoginRoute: LoginRoute,
  RandomRoute: RandomRoute,
  SearchRoute: SearchRoute,
  ApiHeartbeatRoute: ApiHeartbeatRoute,
  ApiLoginRoute: ApiLoginRoute,
  CoverBytextRoute: CoverBytextRoute,
  ImagesIdRoute: ImagesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
