name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install step
        run: "cd website && deno install"

      - name: Build step
        run: "cd website && deno task build"
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "audiobook-covers"
          entrypoint: "main.ts"
          root: "./website"
